/**
 * The backend's machine-readable business-failure codes, as they appear in a problem response's
 * `errorCode` field. The names match the C# `ApiErrorCode` enum, guarded by a backend parity test.
 */
export const BACKEND_ERROR_CODES = [
  'CommentNotFound',
  'NotCommentAuthor',
  'CannotLikeOwnComment',
  'CommentTargetNotFound',
  'CommentProfileIncomplete',
  'ProblemNotFound',
  'ListNotFound',
  'ListAccessDenied',
  'ListReorderMismatch',
  'FavoritesRequireAuthentication',
  'MarkStatusRequiresAuthentication',
  'DefenseSessionNotFound',
  'DefenseContentNotFound',
  'DefenseMessageTooLong',
  'DefenseMessageEmpty',
  'DefenseMessageLimit',
  'DefenseSpendLimit',
  'DefenseRewindTarget',
  'DefenseReportTarget',
  'DefenseFeedbackValue',
  'DefenseFeedbackCommentTooLong',
  'DefenseGradedSessionImmutable',
  'HostedCompetitionNotFound',
  'HostedProblemNotFound',
  'HostedEntryRequired',
  'HostedGroupNotOpen',
  'HostedCompetitionNotReady',
  'HostedEntryAlreadySpent',
  'HostedEntryNotRunning',
  'HostedEntryNotGraded',
  'HostedNoteEmpty',
  'HostedNoteTooLong',
  'HostedEntryProfileIncomplete',
  'AdminNoteValue',
  'AdminNoteTarget',
  'AdminNoteNotFound',
  'NotAdminNoteAuthor',
  'AdminReviewTarget',
  'HostedGroupNotFound',
  'HostedGradeTarget',
  'HostedGradeValue',
  'SelectionTargetNotFound',
  'SelectionBoardOpened',
  'SelectionProposalUsed',
  'SelectionPaperFinalized',
  'SelectionBoardFinalized',
  'SelectionProblemIncomplete',
  'SelectionFinalizeBlocked',
  'ProblemSlugTaken',
  'MalformedRequest',
  'UserNotResolved',
  'UsernameTaken',
  'UsernameAlreadySet',
  'UsernameRejected',
  'ProfileValueInvalid',
  'Unauthenticated',
  'Forbidden',
  'RateLimited',
] as const

/** One of the backend's business-failure codes. */
export type BackendErrorCode = (typeof BACKEND_ERROR_CODES)[number]
