<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="ReadLine" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Spectre.Console.Cli" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MathComps.Shared\MathComps.Shared.csproj" />
  </ItemGroup>

</Project>
