import { SectionNumberingGenerator } from '@/components/shared/utils/section-numbering-utils'
import { slugify } from '@/components/shared/utils/string-utils'
import type { TableOfContentsItem } from '@/components/table-of-contents/table-of-contents-types'

/**
 * Centralized translation keys for guide sections.
 */
export const GUIDE_TITLES = {
  // Main sections
  WHY_COMPETITIONS: 'whyCompetitions',
  COMPETITIONS: 'competitions',
  RESOURCES: 'resources',
  HOW_TO_START: 'howToStart',

  // Competition subsections
  MATH_OLYMPIAD: 'mathOlympiad',
  SEMINARS: 'seminars',
  OTHER_COMPETITIONS: 'otherCompetitions',

  // Seminar subsections
  SEMINARS_ELEMENTARY: 'seminarsElementary',
  SEMINARS_HIGH_SCHOOL: 'seminarsHighSchool',

  // Other competitions subsections
  OTHER_COMPETITIONS_TEAM: 'otherCompetitionsTeam',
  OTHER_COMPETITIONS_INDIVIDUAL: 'otherCompetitionsIndividual',

  // Resource subsections
  WEBSITES: 'websites',
  PROGRAMS: 'programs',
  YOUTUBE: 'youtube',
  STUDY_TEXTS: 'studyTexts',
} as const

/**
 * Union type of all guide title translation keys
 */
type GuideTitleKey = (typeof GUIDE_TITLES)[keyof typeof GUIDE_TITLES]

/**
 * Type definition for a guide section with optional nested children.
 * Used to define the hierarchical structure of the guide navigation.
 */
type GuideSection = {
  /** Translation key for the section title */
  titleKey: GuideTitleKey
  /** Optional nested child sections */
  children?: GuideSection[]
}

/**
 * Static definition of the guide's section hierarchy.
 * This structure mirrors the component tree and is used to generate
 * the table of contents navigation items.
 */
const GUIDE_STRUCTURE: GuideSection[] = [
  {
    titleKey: GUIDE_TITLES.WHY_COMPETITIONS,
  },
  {
    titleKey: GUIDE_TITLES.COMPETITIONS,
    children: [
      {
        titleKey: GUIDE_TITLES.MATH_OLYMPIAD,
      },
      {
        titleKey: GUIDE_TITLES.SEMINARS,
        children: [
          {
            titleKey: GUIDE_TITLES.SEMINARS_ELEMENTARY,
          },
          {
            titleKey: GUIDE_TITLES.SEMINARS_HIGH_SCHOOL,
          },
        ],
      },
      {
        titleKey: GUIDE_TITLES.OTHER_COMPETITIONS,
        children: [
          {
            titleKey: GUIDE_TITLES.OTHER_COMPETITIONS_TEAM,
          },
          {
            titleKey: GUIDE_TITLES.OTHER_COMPETITIONS_INDIVIDUAL,
          },
        ],
      },
    ],
  },
  {
    titleKey: GUIDE_TITLES.RESOURCES,
    children: [
      {
        titleKey: GUIDE_TITLES.WEBSITES,
      },
      {
        titleKey: GUIDE_TITLES.PROGRAMS,
      },
      {
        titleKey: GUIDE_TITLES.YOUTUBE,
      },
      {
        titleKey: GUIDE_TITLES.STUDY_TEXTS,
      },
    ],
  },
  {
    titleKey: GUIDE_TITLES.HOW_TO_START,
  },
]

/**
 * Generates the TOC for the guide component using the provided translation function.
 *
 * @param t Translation function scoped to 'guide.titles' namespace
 *
 * @returns Array of {@link TableOfContentsItem} objects representing the guide's table of contents
 */
export function getGuideTableOfContents(t: (key: GuideTitleKey) => string) {
  // We'll agreggate the result here
  const navigationItems: TableOfContentsItem[] = []

  // Use the shared numbering generator
  const numbering = new SectionNumberingGenerator()

  /**
   * Recursively process a section and its children to build navigation items.
   * Generates hierarchical section numbering (1, 1.1, 1.2, 2, etc.) for TOC display.
   */
  function processSection(section: GuideSection, level: number) {
    // Generate section number using the shared utility
    const sectionNumber = numbering.getNextNumber(level)

    // Resolve localized title (t is already scoped to 'guide.titles')
    const title = t(section.titleKey)

    // Create TOC item with separate number and title fields
    // ID is auto-generated by slugifying the title
    navigationItems.push({
      id: slugify(title),
      label: sectionNumber,
      title: title,
      level: level + 1,
    })

    // Recursively process child sections to maintain hierarchical numbering
    if (section.children) {
      section.children.forEach((child) => processSection(child, level + 1))
    }
  }

  // Handle each section
  GUIDE_STRUCTURE.forEach((section) => processSection(section, 0))

  // The recursive call should have filled this up
  return navigationItems
}
