import { SectionNumberingGenerator } from '@/components/shared/utils/section-numbering-utils'
import { slugify } from '@/components/shared/utils/string-utils'
import type { TableOfContentsItem } from '@/components/table-of-contents/table-of-contents-types'

/**
 * Centralized titles for guide sections.
 */
export const GUIDE_TITLES = {
  // Main sections
  WHY_COMPETITIONS: 'Prečo matematické súťaže?',
  COMPETITIONS: 'Zoznam súťaží',
  RESOURCES: 'Ďalšie odkazy',
  HOW_TO_START: 'Ako začať aj pokračovať',

  // Competition subsections
  MATH_OLYMPIAD: 'Matematická olympiáda',
  SEMINARS: 'Korešpondenčné semináre',
  OTHER_COMPETITIONS: 'Ďalšie súťaže',

  // Seminar subsections
  SEMINARS_ELEMENTARY: 'ZŠ semináre',
  SEMINARS_HIGH_SCHOOL: 'SŠ semináre',

  // Other competitions subsections
  OTHER_COMPETITIONS_TEAM: 'Tímové súťaže',
  OTHER_COMPETITIONS_INDIVIDUAL: 'Individuálne súťaže',

  // Resource subsections
  WEBSITES: 'Webstránky a komunity',
  PROGRAMS: 'Programy a nástroje',
  YOUTUBE: 'YouTube kanály',
  STUDY_TEXTS: 'Študijné texty',
} as const

/**
 * Type definition for a guide section with optional nested children.
 * Used to define the hierarchical structure of the guide navigation.
 */
type GuideSection = {
  /** Display title of the section */
  title: string
  /** Optional nested child sections */
  children?: GuideSection[]
}

/**
 * Static definition of the guide's section hierarchy.
 * This structure mirrors the component tree and is used to generate
 * the table of contents navigation items in a SSR-compatible way.
 */
const GUIDE_STRUCTURE: GuideSection[] = [
  {
    title: GUIDE_TITLES.WHY_COMPETITIONS,
  },
  {
    title: GUIDE_TITLES.COMPETITIONS,
    children: [
      {
        title: GUIDE_TITLES.MATH_OLYMPIAD,
      },
      {
        title: GUIDE_TITLES.SEMINARS,
        children: [
          {
            title: GUIDE_TITLES.SEMINARS_ELEMENTARY,
          },
          {
            title: GUIDE_TITLES.SEMINARS_HIGH_SCHOOL,
          },
        ],
      },
      {
        title: GUIDE_TITLES.OTHER_COMPETITIONS,
        children: [
          {
            title: GUIDE_TITLES.OTHER_COMPETITIONS_TEAM,
          },
          {
            title: GUIDE_TITLES.OTHER_COMPETITIONS_INDIVIDUAL,
          },
        ],
      },
    ],
  },
  {
    title: GUIDE_TITLES.RESOURCES,
    children: [
      {
        title: GUIDE_TITLES.WEBSITES,
      },
      {
        title: GUIDE_TITLES.PROGRAMS,
      },
      {
        title: GUIDE_TITLES.YOUTUBE,
      },
      {
        title: GUIDE_TITLES.STUDY_TEXTS,
      },
    ],
  },
  {
    title: GUIDE_TITLES.HOW_TO_START,
  },
]

/**
 * The pre-calculcate TOC for the guide component
 */
export const guideTableOfContents = (() => {
  // We'll agreggate the result here
  const navigationItems: TableOfContentsItem[] = []

  // Use the shared numbering generator
  const numbering = new SectionNumberingGenerator()

  /**
   * Recursively process a section and its children to build navigation items.
   * Generates hierarchical section numbering (1, 1.1, 1.2, 2, etc.) for TOC display.
   */
  function processSection(section: GuideSection, level: number) {
    // Generate section number using the shared utility
    const sectionNumber = numbering.getNextNumber(level)

    // Create TOC item with separate number and title fields
    // ID is auto-generated by slugifying the title
    navigationItems.push({
      id: slugify(section.title),
      label: sectionNumber,
      title: section.title,
      level: level + 1,
    })

    // Recursively process child sections to maintain hierarchical numbering
    if (section.children) {
      section.children.forEach((child) => processSection(child, level + 1))
    }
  }

  // Handle each section
  GUIDE_STRUCTURE.forEach((section) => processSection(section, 0))

  // The recursive call should have filled this up
  return navigationItems
})()
