<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MathComps.TexParser\MathComps.TexParser.csproj" />
    <ProjectReference Include="..\MathComps.Shared.Cli\MathComps.Shared.Cli.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="PuppeteerSharp" />
    <PackageReference Include="Spectre.Console.Cli" />
  </ItemGroup>

</Project>
