using MathComps.Domain.Constants;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Pgvector;

namespace MathComps.Domain.EfCoreEntities;

/// <summary>
/// Represents a vector embedding for a problem document.
/// Stores embeddings generated by various models for different document types and task types.
/// </summary>
public class ProblemEmbedding
{
    /// <summary>
    /// Primary key.
    /// </summary>
    public Guid Id { get; set; } = Guid.CreateVersion7();

    /// <summary>
    /// Foreign key to the problem text this embedding was generated from.
    /// </summary>
    public required Guid ProblemTextId { get; set; }

    /// <summary>
    /// Navigation to the problem text.
    /// </summary>
    public ProblemText ProblemText { get; set; } = null!;

    /// <summary>
    /// The task type used for embedding generation. This corresponds to the task_type parameter in the Gemini API.
    /// </summary>
    [MaxLength(100)]
    public required string EmbeddingType { get; set; }

    /// <summary>
    /// The internal name of the model that generated this embedding (e.g., "gemini-embedding-001").
    /// </summary>
    [MaxLength(100)]
    public required string ModelName { get; set; }

    /// <summary>
    /// The vector embedding itself.
    /// </summary>
    [Column(TypeName = EmbeddingConstants.VectorColumnType)]
    public required Vector Embedding { get; set; }

    /// <summary>
    /// When this embedding was last updated or generated.
    /// </summary>
    public required DateTime DateUpdated { get; set; }
}
