// <auto-generated />
using System;
using System.Collections.Generic;
using MathComps.Domain.EfCoreEntities;
using MathComps.Domain.Localization;
using MathComps.Domain.Tagging;
using MathComps.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace MathComps.Infrastructure.Migrations
{
    [DbContext(typeof(MathCompsDbContext))]
    partial class MathCompsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "comment_status", new[] { "active", "deleted", "superseded" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "defense_outcome", new[] { "confirmed_the_solution", "found_the_mistake", "not_enough_help", "something_else", "was_off" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "defense_report_category", new[] { "gave_away", "missed_the_mistake", "misunderstood", "other", "said_something_wrong", "tone" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "document_type", new[] { "solution", "statement" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "examiner_step", new[] { "generate", "language_check", "leak_check", "math_check" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "language", new[] { "cs", "en", "sk" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tag_type", new[] { "area", "goal", "technique", "type" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transcript_role", new[] { "candidate", "examiner" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.AdminNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<DefenseReportCategory?>("Category")
                        .HasColumnType("defense_report_category")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid?>("TurnId")
                        .HasColumnType("uuid")
                        .HasColumnName("turn_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_admin_notes");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_admin_note_author_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_admin_note_created_at");

                    b.HasIndex("SessionId", "TurnId")
                        .HasDatabaseName("ix_admin_notes_session_id_turn_id");

                    b.ToTable("admin_notes", null, t =>
                        {
                            t.HasCheckConstraint("ck_admin_note_content_not_blank", "coalesce(btrim(content, E' \\t\\n\\r\\f'), '') <> ''");
                        });
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.AdminSessionReview", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<DateTimeOffset>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.HasKey("SessionId", "ReviewerId")
                        .HasName("pk_admin_session_reviews");

                    b.HasIndex("ReviewerId")
                        .HasDatabaseName("ix_admin_session_reviews_reviewer_id");

                    b.ToTable("admin_session_reviews", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_authors");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_author_slug");

                    b.ToTable("authors", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment_id");

                    b.Property<Guid?>("PreviousVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_version_id");

                    b.Property<CommentStatus>("Status")
                        .HasColumnType("comment_status")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_comment_author_id");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_comment_parent_id");

                    b.HasIndex("PreviousVersionId")
                        .HasDatabaseName("ix_comments_previous_version_id");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.CommentLike", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "CommentId")
                        .HasName("pk_comment_likes");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_comment_like_comment_id");

                    b.ToTable("comment_likes", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("path");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("SortPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sort_path");

                    b.HasKey("Id")
                        .HasName("pk_competitions");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("ux_competition_path");

                    b.HasIndex("SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_competition_root_sort_order")
                        .HasFilter("\"parent_id\" IS NULL");

                    b.HasIndex("ParentId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_competition_parent_sort_order")
                        .HasFilter("\"parent_id\" IS NOT NULL");

                    b.ToTable("competitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_competition_slug_has_no_hyphen", "position('-' in \"slug\") = 0");

                            t.HasCheckConstraint("ck_competition_sort_order_positive", "\"sort_order\" > 0");
                        });
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.DefenseAttemptCall", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<int>("CachedPromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("cached_prompt_tokens");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<string>("ReasoningEffort")
                        .HasColumnType("text")
                        .HasColumnName("reasoning_effort");

                    b.Property<int>("ReasoningTokens")
                        .HasColumnType("integer")
                        .HasColumnName("reasoning_tokens");

                    b.Property<ExaminerStep>("Step")
                        .HasColumnType("examiner_step")
                        .HasColumnName("step");

                    b.HasKey("Id")
                        .HasName("pk_defense_attempt_calls");

                    b.HasIndex("AttemptId")
                        .HasDatabaseName("ix_defense_attempt_calls_attempt_id");

                    b.ToTable("defense_attempt_calls", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.DefenseSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExaminerConfig")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("examiner_config");

                    b.Property<string>("ProblemReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("problem_reference");

                    b.Property<string>("ProblemStatement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("problem_statement");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_defense_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_defense_session_user_id");

                    b.ToTable("defense_sessions", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.DefenseSessionFeedback", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DefenseOutcome>("Outcome")
                        .HasColumnType("defense_outcome")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SessionId")
                        .HasName("pk_defense_session_feedbacks");

                    b.ToTable("defense_session_feedbacks", null, t =>
                        {
                            t.HasCheckConstraint("ck_defense_session_feedback_something_else_needs_comment", "outcome <> 'something_else' OR coalesce(btrim(comment, E' \\t\\n\\r\\f'), '') <> ''");
                        });
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.DefenseSpend", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CachedPromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("cached_prompt_tokens");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<int>("ReasoningTokens")
                        .HasColumnType("integer")
                        .HasColumnName("reasoning_tokens");

                    b.Property<int>("Revisions")
                        .HasColumnType("integer")
                        .HasColumnName("revisions");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_defense_spends");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_defense_spend_user_id_created_at");

                    b.ToTable("defense_spends", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.DefenseTurn", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<TranscriptRole>("Role")
                        .HasColumnType("transcript_role")
                        .HasColumnName("role");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_defense_turns");

                    b.HasAlternateKey("SessionId", "Id")
                        .HasName("ak_defense_turns_session_id_id");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_defense_turn_session_id_sequence");

                    b.ToTable("defense_turns", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.DefenseTurnAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptIndex")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_index");

                    b.Property<string>("CandidateLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("candidate_language");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Established")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("established");

                    b.Property<bool>("IsSafeFallback")
                        .HasColumnType("boolean")
                        .HasColumnName("is_safe_fallback");

                    b.Property<bool>("Leaks")
                        .HasColumnType("boolean")
                        .HasColumnName("leaks");

                    b.Property<string>("MathCorrection")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("math_correction");

                    b.Property<bool>("MathHolds")
                        .HasColumnType("boolean")
                        .HasColumnName("math_holds");

                    b.Property<string>("Reply")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reply");

                    b.Property<string>("RevisionNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("revision_note");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<bool>("SwitchesLanguage")
                        .HasColumnType("boolean")
                        .HasColumnName("switches_language");

                    b.Property<Guid>("TurnId")
                        .HasColumnType("uuid")
                        .HasColumnName("turn_id");

                    b.Property<string>("WhatLeaked")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("what_leaked");

                    b.Property<bool>("WithholdsClose")
                        .HasColumnType("boolean")
                        .HasColumnName("withholds_close");

                    b.HasKey("Id")
                        .HasName("pk_defense_turn_attempts");

                    b.HasIndex("SessionId", "TurnId")
                        .HasDatabaseName("ix_defense_turn_attempts_session_id_turn_id");

                    b.HasIndex("TurnId", "AttemptIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_defense_turn_attempt_turn_id_attempt_index");

                    b.ToTable("defense_turn_attempts", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.DefenseTurnReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<DefenseReportCategory>>("Categories")
                        .IsRequired()
                        .HasColumnType("defense_report_category[]")
                        .HasColumnName("categories");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("TurnId")
                        .HasColumnType("uuid")
                        .HasColumnName("turn_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_defense_turn_reports");

                    b.HasIndex("TurnId")
                        .IsUnique()
                        .HasDatabaseName("ux_defense_turn_report_turn_id");

                    b.HasIndex("SessionId", "TurnId")
                        .IsUnique()
                        .HasDatabaseName("ux_defense_turn_report_session_id_turn_id");

                    b.ToTable("defense_turn_reports", null, t =>
                        {
                            t.HasCheckConstraint("ck_defense_turn_report_categories_not_empty", "cardinality(categories) > 0");

                            t.HasCheckConstraint("ck_defense_turn_report_other_needs_comment", "NOT ('other' = ANY(categories)) OR coalesce(btrim(comment, E' \\t\\n\\r\\f'), '') <> ''");
                        });
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.Handout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("content_id");

                    b.HasKey("Id")
                        .HasName("pk_handouts");

                    b.HasIndex("ContentId")
                        .IsUnique()
                        .HasDatabaseName("ux_handout_content_id");

                    b.ToTable("handouts", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.HandoutComment", b =>
                {
                    b.Property<Guid>("HandoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("handout_id");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.HasKey("HandoutId", "CommentId")
                        .HasName("pk_handout_comments");

                    b.HasIndex("CommentId")
                        .IsUnique()
                        .HasDatabaseName("ux_handout_comment_comment_id");

                    b.ToTable("handout_comments", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.HandoutEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_id");

                    b.Property<Guid>("HandoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("handout_id");

                    b.HasKey("Id")
                        .HasName("pk_handout_environments");

                    b.HasIndex("HandoutId", "ContentId")
                        .IsUnique()
                        .HasDatabaseName("ux_handout_environment_handout_id_content_id");

                    b.ToTable("handout_environments", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.HandoutEnvironmentDefense", b =>
                {
                    b.Property<Guid>("DefenseSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("defense_session_id");

                    b.Property<Guid>("HandoutEnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("handout_environment_id");

                    b.HasKey("DefenseSessionId")
                        .HasName("pk_handout_environment_defenses");

                    b.HasIndex("HandoutEnvironmentId")
                        .HasDatabaseName("ix_handout_environment_defense_handout_environment_id");

                    b.ToTable("handout_environment_defenses", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.NewsArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("content_id");

                    b.HasKey("Id")
                        .HasName("pk_news_articles");

                    b.HasIndex("ContentId")
                        .IsUnique()
                        .HasDatabaseName("ux_news_article_content_id");

                    b.ToTable("news_articles", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.NewsArticleComment", b =>
                {
                    b.Property<Guid>("NewsArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("news_article_id");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.HasKey("NewsArticleId", "CommentId")
                        .HasName("pk_news_article_comments");

                    b.HasIndex("CommentId")
                        .IsUnique()
                        .HasDatabaseName("ux_news_article_comment_comment_id");

                    b.ToTable("news_article_comments", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<string>("SolutionLink")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("solution_link");

                    b.HasKey("Id")
                        .HasName("pk_problems");

                    b.HasIndex("RoundId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ux_problem_round_number");

                    b.ToTable("problems", null, t =>
                        {
                            t.HasCheckConstraint("ck_problem_number_positive", "\"number\" > 0");
                        });
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.ProblemAuthor", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("ProblemId", "AuthorId")
                        .HasName("pk_problem_authors");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_problem_author_author_id");

                    b.HasIndex("ProblemId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_problem_author_problem_ordinal");

                    b.ToTable("problem_authors", null, t =>
                        {
                            t.HasCheckConstraint("ck_problem_author_order_positive", "\"ordinal\" > 0");
                        });
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.ProblemComment", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.HasKey("ProblemId", "CommentId")
                        .HasName("pk_problem_comments");

                    b.HasIndex("CommentId")
                        .IsUnique()
                        .HasDatabaseName("ux_problem_comment_comment_id");

                    b.ToTable("problem_comments", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.ProblemEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_updated");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("embedding_type");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<Guid>("ProblemTextId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_text_id");

                    b.HasKey("Id")
                        .HasName("pk_problem_embeddings");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_problem_embedding_cosine")
                        .HasAnnotation("Npgsql:StorageParameter:lists", 100);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "ivfflat");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("ProblemTextId")
                        .HasDatabaseName("ix_problem_embedding_problem_text_id");

                    b.HasIndex("ProblemTextId", "EmbeddingType", "ModelName")
                        .IsUnique()
                        .HasDatabaseName("ux_problem_embedding_text_embedding_model");

                    b.ToTable("problem_embeddings", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.ProblemLike", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "ProblemId")
                        .HasName("pk_problem_likes");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_problem_like_problem_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_problem_like_user_id");

                    b.ToTable("problem_likes", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.ProblemMarkStatus", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "ProblemId")
                        .HasName("pk_problem_mark_statuses");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_problem_mark_status_problem_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_problem_mark_status_user_id");

                    b.ToTable("problem_mark_statuses", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.ProblemSimilarity", b =>
                {
                    b.Property<Guid>("SourceProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_problem_id");

                    b.Property<Guid>("SimilarProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("similar_problem_id");

                    b.Property<double>("SimilarityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("similarity_score");

                    b.HasKey("SourceProblemId", "SimilarProblemId")
                        .HasName("pk_problem_similarities");

                    b.HasIndex("SimilarProblemId")
                        .HasDatabaseName("ix_problem_similarity_similar_problem_id");

                    b.ToTable("problem_similarities", null, t =>
                        {
                            t.HasCheckConstraint("ck_problem_similarity_not_self", "\"source_problem_id\" <> \"similar_problem_id\"");
                        });
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.ProblemTag", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<int?>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<float>("GoodnessOfFit")
                        .HasColumnType("real")
                        .HasColumnName("goodness_of_fit");

                    b.Property<string>("Justification")
                        .HasColumnType("text")
                        .HasColumnName("justification");

                    b.HasKey("ProblemId", "TagId")
                        .HasName("pk_problem_tag");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_problem_tag_problem_id");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_problem_tag_tag_id");

                    b.ToTable("problem_tag", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.ProblemText", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_modified");

                    b.Property<DocumentType>("DocumentType")
                        .HasColumnType("document_type")
                        .HasColumnName("document_type");

                    b.Property<bool>("IsOriginal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_original");

                    b.Property<Language>("Language")
                        .HasColumnType("language")
                        .HasColumnName("language");

                    b.Property<string>("MarkdownText")
                        .HasColumnType("text")
                        .HasColumnName("markdown_text");

                    b.Property<string>("ParsedText")
                        .HasColumnType("jsonb")
                        .HasColumnName("parsed_text");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.HasKey("Id")
                        .HasName("pk_problem_texts");

                    b.HasIndex("MarkdownText")
                        .HasDatabaseName("ix_problem_text_search_trgm")
                        .HasAnnotation("Npgsql:IndexExpression", "immutable_unaccent(coalesce(markdown_text, raw_text))");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MarkdownText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("MarkdownText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_problem_text_problem_id");

                    b.HasIndex("ProblemId", "DocumentType")
                        .IsUnique()
                        .HasDatabaseName("ux_problem_text_one_original_per_problem_document")
                        .HasFilter("is_original = true");

                    b.HasIndex("ProblemId", "DocumentType", "Language")
                        .IsUnique()
                        .HasDatabaseName("ux_problem_text_problem_document_language");

                    b.HasIndex("ProblemId", "Language", "IsOriginal")
                        .HasDatabaseName("ix_problem_text_statement_lookup")
                        .HasFilter("document_type = 'statement' AND markdown_text IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("ProblemId", "Language", "IsOriginal"), new[] { "MarkdownText" });

                    b.ToTable("problem_texts", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<DateTimeOffset?>("VisibleSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visible_since");

                    b.HasKey("Id")
                        .HasName("pk_rounds");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_rounds_season_id");

                    b.HasIndex("CompetitionId", "SeasonId")
                        .IsUnique()
                        .HasDatabaseName("ux_round_competition_season");

                    b.ToTable("rounds", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("EditionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("edition_number");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer")
                        .HasColumnName("start_year");

                    b.HasKey("Id")
                        .HasName("pk_seasons");

                    b.HasIndex("EditionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_season_edition_number");

                    b.HasIndex("StartYear")
                        .IsUnique()
                        .HasDatabaseName("ux_season_start_year");

                    b.ToTable("seasons", null, t =>
                        {
                            t.HasCheckConstraint("ck_season_edition_positive", "\"edition_number\" > 0");

                            t.HasCheckConstraint("ck_season_start_year_sane", "\"start_year\" >= 1900");
                        });
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<TagType>("TagType")
                        .HasColumnType("tag_type")
                        .HasColumnName("tag_type");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_tag_slug");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset?>("ConsentedToAiAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consented_to_ai_at");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<int?>("GraduationYear")
                        .HasColumnType("integer")
                        .HasColumnName("graduation_year");

                    b.Property<bool>("HasLeftHighSchool")
                        .HasColumnType("boolean")
                        .HasColumnName("has_left_high_school");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_external_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.UserProblemList", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentId")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("content_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shared");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_problem_lists");

                    b.HasIndex("ContentId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_problem_list_content_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_problem_list_user_id");

                    b.ToTable("user_problem_lists", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_problem_list_sort_order_positive", "\"sort_order\" > 0");
                        });
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.UserProblemListItem", b =>
                {
                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid")
                        .HasColumnName("list_id");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.HasKey("ListId", "ProblemId")
                        .HasName("pk_user_problem_list_items");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_user_problem_list_item_problem_id");

                    b.ToTable("user_problem_list_items", (string)null);
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.AdminNote", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_admin_notes_users_author_id");

                    b.HasOne("MathComps.Domain.EfCoreEntities.DefenseSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_notes_defense_sessions_session_id");

                    b.HasOne("MathComps.Domain.EfCoreEntities.DefenseTurn", "Turn")
                        .WithMany()
                        .HasForeignKey("SessionId", "TurnId")
                        .HasPrincipalKey("SessionId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_admin_notes_defense_turns_session_id_turn_id");

                    b.Navigation("Author");

                    b.Navigation("Session");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.AdminSessionReview", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_session_reviews_users_reviewer_id");

                    b.HasOne("MathComps.Domain.EfCoreEntities.DefenseSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_session_reviews_defense_sessions_session_id");

                    b.Navigation("Reviewer");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.Comment", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_author_id");

                    b.HasOne("MathComps.Domain.EfCoreEntities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comments_comments_parent_comment_id");

                    b.HasOne("MathComps.Domain.EfCoreEntities.Comment", "PreviousVersion")
                        .WithMany()
                        .HasForeignKey("PreviousVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comments_comments_previous_version_id");

                    b.Navigation("Author");

                    b.Navigation("ParentComment");

                    b.Navigation("PreviousVersion");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.CommentLike", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.Comment", "Comment")
                        .WithMany("Likes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_likes_comments_comment_id");

                    b.HasOne("MathComps.Domain.EfCoreEntities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_likes_users_user_id");

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.Competition", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.Competition", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_competitions_competitions_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.DefenseAttemptCall", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.DefenseTurnAttempt", "Attempt")
                        .WithMany("Calls")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_defense_attempt_calls_defense_turn_attempts_attempt_id");

                    b.Navigation("Attempt");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.DefenseSession", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_defense_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.DefenseSessionFeedback", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.DefenseSession", "Session")
                        .WithOne("Feedback")
                        .HasForeignKey("MathComps.Domain.EfCoreEntities.DefenseSessionFeedback", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_defense_session_feedbacks_defense_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.DefenseTurn", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.DefenseSession", "Session")
                        .WithMany("Turns")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_defense_turns_defense_sessions_session_id");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.DefenseTurnAttempt", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.DefenseSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_defense_turn_attempts_defense_sessions_session_id");

                    b.HasOne("MathComps.Domain.EfCoreEntities.DefenseTurn", "Turn")
                        .WithMany("Attempts")
                        .HasForeignKey("SessionId", "TurnId")
                        .HasPrincipalKey("SessionId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_defense_turn_attempts_defense_turns_session_id_turn_id");

                    b.Navigation("Session");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.DefenseTurnReport", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.DefenseSession", "Session")
                        .WithMany("Reports")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_defense_turn_reports_defense_sessions_session_id");

                    b.HasOne("MathComps.Domain.EfCoreEntities.DefenseTurn", "Turn")
                        .WithOne()
                        .HasForeignKey("MathComps.Domain.EfCoreEntities.DefenseTurnReport", "SessionId", "TurnId")
                        .HasPrincipalKey("MathComps.Domain.EfCoreEntities.DefenseTurn", "SessionId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_defense_turn_reports_defense_turns_session_id_turn_id");

                    b.Navigation("Session");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.HandoutComment", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_handout_comments_comments_comment_id");

                    b.HasOne("MathComps.Domain.EfCoreEntities.Handout", "Handout")
                        .WithMany("Comments")
                        .HasForeignKey("HandoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_handout_comments_handouts_handout_id");

                    b.Navigation("Comment");

                    b.Navigation("Handout");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.HandoutEnvironment", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.Handout", "Handout")
                        .WithMany("Environments")
                        .HasForeignKey("HandoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_handout_environments_handouts_handout_id");

                    b.Navigation("Handout");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.HandoutEnvironmentDefense", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.DefenseSession", "DefenseSession")
                        .WithOne("EnvironmentTarget")
                        .HasForeignKey("MathComps.Domain.EfCoreEntities.HandoutEnvironmentDefense", "DefenseSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_handout_environment_defenses_defense_sessions_defense_sessi");

                    b.HasOne("MathComps.Domain.EfCoreEntities.HandoutEnvironment", "HandoutEnvironment")
                        .WithMany("Defenses")
                        .HasForeignKey("HandoutEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_handout_environment_defenses_handout_environments_handout_e");

                    b.Navigation("DefenseSession");

                    b.Navigation("HandoutEnvironment");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.NewsArticleComment", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_article_comments_comments_comment_id");

                    b.HasOne("MathComps.Domain.EfCoreEntities.NewsArticle", "NewsArticle")
                        .WithMany("Comments")
                        .HasForeignKey("NewsArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_article_comments_news_articles_news_article_id");

                    b.Navigation("Comment");

                    b.Navigation("NewsArticle");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.Problem", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.Round", "Round")
                        .WithMany("Problems")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problems_rounds_round_id");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.ProblemAuthor", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.Author", "Author")
                        .WithMany("ProblemAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_problem_authors_authors_author_id");

                    b.HasOne("MathComps.Domain.EfCoreEntities.Problem", "Problem")
                        .WithMany("ProblemAuthors")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_authors_problems_problem_id");

                    b.Navigation("Author");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.ProblemComment", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_comments_comments_comment_id");

                    b.HasOne("MathComps.Domain.EfCoreEntities.Problem", "Problem")
                        .WithMany("ProblemComments")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_comments_problems_problem_id");

                    b.Navigation("Comment");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.ProblemEmbedding", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.ProblemText", "ProblemText")
                        .WithMany("Embeddings")
                        .HasForeignKey("ProblemTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_embeddings_problem_texts_problem_text_id");

                    b.Navigation("ProblemText");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.ProblemLike", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.Problem", "Problem")
                        .WithMany("Likes")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_likes_problems_problem_id");

                    b.HasOne("MathComps.Domain.EfCoreEntities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_likes_users_user_id");

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.ProblemMarkStatus", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.Problem", "Problem")
                        .WithMany("MarkStatuses")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_mark_statuses_problems_problem_id");

                    b.HasOne("MathComps.Domain.EfCoreEntities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_mark_statuses_users_user_id");

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.ProblemSimilarity", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.Problem", "SimilarProblem")
                        .WithMany("AppearsInProblems")
                        .HasForeignKey("SimilarProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_similarities_problems_similar_problem_id");

                    b.HasOne("MathComps.Domain.EfCoreEntities.Problem", "SourceProblem")
                        .WithMany("SimilarProblems")
                        .HasForeignKey("SourceProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_similarities_problems_source_problem_id");

                    b.OwnsOne("MathComps.Domain.SimilarityComponents", "Components", b1 =>
                        {
                            b1.Property<Guid>("ProblemSimilaritySourceProblemId");

                            b1.Property<Guid>("ProblemSimilaritySimilarProblemId");

                            b1.Property<double>("CompetitionSimilarity");

                            b1.Property<double?>("SolutionSimilarity");

                            b1.Property<double>("StatementSimilarity");

                            b1.Property<double>("TagSimilarity");

                            b1.HasKey("ProblemSimilaritySourceProblemId", "ProblemSimilaritySimilarProblemId");

                            b1.ToTable("problem_similarities");

                            b1
                                .ToJson("components")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProblemSimilaritySourceProblemId", "ProblemSimilaritySimilarProblemId")
                                .HasConstraintName("fk_problem_similarities_problem_similarities_source_problem_id");
                        });

                    b.Navigation("Components");

                    b.Navigation("SimilarProblem");

                    b.Navigation("SourceProblem");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.ProblemTag", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.Problem", "Problem")
                        .WithMany("ProblemTagsAll")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_tag_problems_problem_id");

                    b.HasOne("MathComps.Domain.EfCoreEntities.Tag", "Tag")
                        .WithMany("ProblemTagsAll")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_tag_tags_tag_id");

                    b.Navigation("Problem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.ProblemText", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.Problem", "Problem")
                        .WithMany("Texts")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_texts_problems_problem_id");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.Round", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rounds_competitions_competition_id");

                    b.HasOne("MathComps.Domain.EfCoreEntities.Season", "Season")
                        .WithMany("Rounds")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rounds_seasons_season_id");

                    b.Navigation("Competition");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.UserProblemList", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_problem_lists_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.UserProblemListItem", b =>
                {
                    b.HasOne("MathComps.Domain.EfCoreEntities.UserProblemList", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_problem_list_items_user_problem_lists_list_id");

                    b.HasOne("MathComps.Domain.EfCoreEntities.Problem", "Problem")
                        .WithMany("UserProblemListItems")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_problem_list_items_problems_problem_id");

                    b.Navigation("List");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.Author", b =>
                {
                    b.Navigation("ProblemAuthors");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.Comment", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.Competition", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.DefenseSession", b =>
                {
                    b.Navigation("EnvironmentTarget");

                    b.Navigation("Feedback");

                    b.Navigation("Reports");

                    b.Navigation("Turns");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.DefenseTurn", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.DefenseTurnAttempt", b =>
                {
                    b.Navigation("Calls");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.Handout", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Environments");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.HandoutEnvironment", b =>
                {
                    b.Navigation("Defenses");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.NewsArticle", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.Problem", b =>
                {
                    b.Navigation("AppearsInProblems");

                    b.Navigation("Likes");

                    b.Navigation("MarkStatuses");

                    b.Navigation("ProblemAuthors");

                    b.Navigation("ProblemComments");

                    b.Navigation("ProblemTagsAll");

                    b.Navigation("SimilarProblems");

                    b.Navigation("Texts");

                    b.Navigation("UserProblemListItems");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.ProblemText", b =>
                {
                    b.Navigation("Embeddings");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.Round", b =>
                {
                    b.Navigation("Problems");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.Season", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.Tag", b =>
                {
                    b.Navigation("ProblemTagsAll");
                });

            modelBuilder.Entity("MathComps.Domain.EfCoreEntities.UserProblemList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
