using MathComps.Domain.Contracts.UserLists;
using MathComps.Domain.EfCoreEntities;
using MathComps.Infrastructure.Persistence;
using MathComps.Infrastructure.Services.Problems;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Collections.Immutable;

namespace MathComps.Infrastructure.Services.Users;

/// <summary>
/// Service for managing user problem lists in the database.
/// </summary>
/// <param name="dbContext">The database context.</param>
/// <param name="problemLookup">Resolves problem slugs to internal ids.</param>
/// <param name="logger">The logger.</param>
public class UserListService(
    MathCompsDbContext dbContext,
    IProblemLookupService problemLookup,
    ILogger<UserListService> logger) : IUserListService
{
    /// <inheritdoc />
    public async Task<UserListsResponse> GetListsAsync(Guid userId)
    {
        // Count liked problems from the separate ProblemLike system
        var likedCount = await dbContext.ProblemLikes
            .CountAsync(like => like.UserId == userId);

        // Fetch all lists for the user, ordered by sort order
        var lists = await dbContext.UserProblemLists
            .Where(list => list.UserId == userId)
            .OrderBy(list => list.SortOrder)
            .Select(list => new UserListDto(
                list.ContentId,
                list.Name,
                list.Items.Count,
                list.IsShared
            ))
            .ToListAsync();

        // Bundle liked count with lists
        return new UserListsResponse(likedCount, [.. lists]);
    }

    /// <inheritdoc />
    public async Task<UserListDto> CreateListAsync(Guid userId, string name)
    {
        // Determine the next sort order (after all existing lists)
        var maxSortOrder = await dbContext.UserProblemLists
            .Where(list => list.UserId == userId)
            .MaxAsync(list => (int?)list.SortOrder) ?? 0;

        // Create the new list entity (ContentId is auto-generated by Nanoid)
        var now = DateTimeOffset.UtcNow;
        var list = new UserProblemList
        {
            UserId = userId,
            Name = name.Trim(),
            SortOrder = maxSortOrder + 1,
            CreatedAt = now,
            UpdatedAt = now
        };

        // Add to the database
        dbContext.UserProblemLists.Add(list);
        await dbContext.SaveChangesAsync();

        // Log the creation
        logger.LogInformation("Created list '{ContentId}' for user {UserId}", list.ContentId, userId);

        // Return the created list
        return new UserListDto(list.ContentId, list.Name, ProblemCount: 0, list.IsShared);
    }

    /// <inheritdoc />
    public async Task<UserListDto> UpdateListAsync(Guid userId, string contentId, string newName)
    {
        // Find the list by content ID
        var list = await dbContext.UserProblemLists
            .Include(list => list.Items)
            .FirstOrDefaultAsync(list => list.UserId == userId && list.ContentId == contentId)
            // It must exist
            ?? throw new ListNotFoundException(contentId);

        // Update only the display name (content ID stays stable)
        list.Name = newName.Trim();
        list.UpdatedAt = DateTimeOffset.UtcNow;

        // Save changes
        await dbContext.SaveChangesAsync();

        // Log the update
        logger.LogInformation("Renamed list '{ContentId}' to '{NewName}' for user {UserId}", contentId, newName, userId);

        // Return the updated list
        return new UserListDto(list.ContentId, list.Name, list.Items.Count, list.IsShared);
    }

    /// <inheritdoc />
    public async Task DeleteListAsync(Guid userId, string contentId)
    {
        // Find the list by content ID
        var list = await dbContext.UserProblemLists
            .FirstOrDefaultAsync(list => list.UserId == userId && list.ContentId == contentId)
            // It must exist
            ?? throw new ListNotFoundException(contentId);

        // Remove the list (cascade deletes items)
        dbContext.UserProblemLists.Remove(list);
        await dbContext.SaveChangesAsync();

        // Log the deletion
        logger.LogInformation("Deleted list '{ContentId}' for user {UserId}", contentId, userId);
    }

    /// <inheritdoc />
    public async Task AddProblemAsync(Guid userId, string contentId, string problemSlug)
    {
        // Resolve slug to internal ID (throws if the problem doesn't exist)
        var problemId = await problemLookup.GetRequiredProblemIdBySlugAsync(problemSlug);

        // Find the list (verify ownership)
        var list = await dbContext.UserProblemLists
            .FirstOrDefaultAsync(list => list.UserId == userId && list.ContentId == contentId)
            // It must exist
            ?? throw new ListNotFoundException(contentId);

        // Check if the problem is already in the list (idempotent)
        var alreadyExists = await dbContext.UserProblemListItems
            .AnyAsync(item => item.ListId == list.Id && item.ProblemId == problemId);

        // If already in the list, do nothing
        if (alreadyExists)
            return;

        // Add the problem to the list
        dbContext.UserProblemListItems.Add(new UserProblemListItem
        {
            ListId = list.Id,
            ProblemId = problemId,
            AddedAt = DateTimeOffset.UtcNow
        });

        // Save changes
        await dbContext.SaveChangesAsync();

        // Log the addition
        logger.LogInformation("Added problem '{ProblemSlug}' to list '{ContentId}' for user {UserId}", problemSlug, contentId, userId);
    }

    /// <inheritdoc />
    public async Task RemoveProblemAsync(Guid userId, string contentId, string problemSlug)
    {
        // Resolve slug to internal ID (throws if the problem doesn't exist)
        var problemId = await problemLookup.GetRequiredProblemIdBySlugAsync(problemSlug);

        // Find the list (verify ownership)
        var list = await dbContext.UserProblemLists
            .FirstOrDefaultAsync(list => list.UserId == userId && list.ContentId == contentId)
            // It must exist
            ?? throw new ListNotFoundException(contentId);

        // Find the item to remove
        var item = await dbContext.UserProblemListItems
            .FirstOrDefaultAsync(item => item.ListId == list.Id && item.ProblemId == problemId);

        // If the problem isn't in the list, do nothing
        if (item == null)
            return;

        // Remove the item
        dbContext.UserProblemListItems.Remove(item);
        await dbContext.SaveChangesAsync();

        // Log the removal
        logger.LogInformation("Removed problem '{ProblemSlug}' from list '{ContentId}' for user {UserId}", problemSlug, contentId, userId);
    }

    /// <inheritdoc />
    public async Task ReorderListsAsync(Guid userId, ImmutableList<string> contentIds)
    {
        // Load all lists for the user
        var lists = await dbContext.UserProblemLists
            .Where(list => list.UserId == userId)
            .ToListAsync();

        // Validate that the content ID set matches exactly (no missing, no extra)
        var existingIds = lists.Select(list => list.ContentId).ToHashSet();
        var requestedIds = contentIds.ToHashSet();

        // Check for mismatches
        if (!existingIds.SetEquals(requestedIds))
            throw new ListReorderMismatchException();

        // Build a content-ID-to-position map for O(1) lookups
        var idOrder = contentIds
            .Select((id, index) => (id, order: index + 1))
            .ToDictionary(pair => pair.id, pair => pair.order);

        // Assign sort orders based on position in the array
        foreach (var list in lists)
        {
            list.SortOrder = idOrder[list.ContentId];
            list.UpdatedAt = DateTimeOffset.UtcNow;
        }

        // Save all changes atomically
        await dbContext.SaveChangesAsync();

        // Log the reorder
        logger.LogInformation("Reordered {Count} lists for user {UserId}", lists.Count, userId);
    }

    /// <inheritdoc />
    public async Task<UserListDto> SetSharingAsync(Guid userId, string contentId, bool enabled)
    {
        // Find the list by content ID
        var list = await dbContext.UserProblemLists
            .Include(list => list.Items)
            .FirstOrDefaultAsync(list => list.UserId == userId && list.ContentId == contentId)
            // It must exist
            ?? throw new ListNotFoundException(contentId);

        // Update sharing status
        list.IsShared = enabled;
        list.UpdatedAt = DateTimeOffset.UtcNow;

        // Save changes
        await dbContext.SaveChangesAsync();

        // Log the change
        logger.LogInformation("{Action} sharing for list '{ContentId}' for user {UserId}",
            enabled ? "Enabled" : "Disabled", contentId, userId);

        // Return the updated list
        return new UserListDto(list.ContentId, list.Name, list.Items.Count, list.IsShared);
    }

    /// <inheritdoc />
    public async Task<ListAccessResult> CheckListAccessAsync(Guid? userId, string contentId)
    {
        // Check if the list exists and whether the user can access it
        var list = await dbContext.UserProblemLists
            .Where(list => list.ContentId == contentId)
            .Select(list => new { list.UserId, list.IsShared, list.Name })
            .FirstOrDefaultAsync();

        // Non-existent list
        if (list is null)
            return new ListAccessResult(ListAccessStatus.NotFound);

        // Owner always has access, others only if shared
        var isOwner = userId.HasValue && list.UserId == userId.Value;
        return isOwner || list.IsShared
            ? new ListAccessResult(ListAccessStatus.HasAccess, list.Name)
            : new ListAccessResult(ListAccessStatus.NoAccess);
    }
}
